# Generated by Django 2.0.5 on 2018-05-29 07:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='')),
                ('fb_social_link', models.URLField()),
                ('twitter_social_link', models.URLField()),
                ('linkedin_social_link', models.URLField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2018, 5, 29, 7, 29, 31, 118440, tzinfo=utc))),
            ],
        ),
    ]
