# Generated by Django 2.0.5 on 2018-05-29 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2018, 5, 29, 8, 2, 20, 140948, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date_added', models.DateTimeField(default=datetime.datetime(2018, 5, 29, 8, 2, 20, 140948, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 8, 2, 20, 128955, tzinfo=utc)),
        ),
    ]
