# Generated by Django 2.0.5 on 2018-05-29 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20180529_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 9, 9, 57, 925752, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 9, 9, 57, 924753, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 29, 9, 9, 57, 913760, tzinfo=utc)),
        ),
    ]
