# Generated by Django 2.0.6 on 2018-06-04 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20180529_1409'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 10, 20, 5, 639461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 4, 10, 20, 5, 608211, tzinfo=utc)),
        ),
    ]
