# Generated by Django 2.0.6 on 2018-06-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_auto_20180605_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='clients/logo')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(null=True, upload_to='image/%Y/%m/%D'),
        ),
    ]
