# Generated by Django 2.0.6 on 2018-06-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0006_auto_20180605_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='fb_social_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_social_link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_social_link',
            field=models.URLField(null=True),
        ),
    ]
