# Generated by Django 2.0.6 on 2018-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0008_auto_20180605_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='picture',
        ),
        migrations.AddField(
            model_name='team',
            name='pic',
            field=models.ImageField(null=True, upload_to='team/%Y'),
        ),
    ]
