# Generated by Django 2.0.6 on 2018-06-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0009_auto_20180605_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='pic',
        ),
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='team/%y'),
        ),
    ]
