# Generated by Django 2.0.6 on 2018-06-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0010_auto_20180606_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.IntegerField(blank=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
