# Generated by Django 2.0.6 on 2018-06-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0012_footerlinks_privacy_termsofuse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
    ]
