# Generated by Django 2.0.6 on 2018-06-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0013_delete_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlinks',
            name='facebook',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='footerlinks',
            name='twitter',
            field=models.URLField(),
        ),
    ]
