# Generated by Django 2.0.6 on 2018-06-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0016_auto_20180612_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
