# Generated by Django 2.0.6 on 2018-06-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0017_auto_20180613_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='details',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
