# Generated by Django 2.0.6 on 2018-06-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0018_auto_20180613_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='details',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
